# 数据库配置
spring:
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 724721900@qq.com
    #QQ邮箱的授权码
    password: nfwapzuvndtvbcef
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #不加这句则默认为myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 47.93.216.116
    port: 6379
    password: ${PASSWORD}
    database: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0

  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 100MB
      # 单个文件的最大值
      max-file-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 服务
server:
  port: 80
# 文件上传路径配置
file:
  # 静态资源对外暴露的访问路径
  staticAccessPath: /static/files/**
  #文件上传目录
  uploadFolder: E:/javaAndMore/projectspace/jbhim/public/files/
  staticAccessUrl: http://localhost/static/files/


#设置一个邮件发送人
jbhim:
  mail:
    sender: 724721900@qq.com

wechat:
  token: xxxxxxxx
  # 信息绑定页面路由
  bindOpenIdPage: https://rc-dev-cust-test-mobile.ywsoftware.cn:9443/public-registration
  # 微信获取code 回调地址(需要在微信开发者中心配置域名)
  codeRedirectUrl: https://rc-dev-cust-test2298.ywsoftware.cn:9443/cust-api/wechat/userInfo
  mp:
    appId: wx7576f64beebc6725
    appSecret: 708c6dc168eecec0212ff55beb673208
    templateId:
      #任务转移模板消息id
      taskTransfer: JUQP6KkPUDJ-qzMiIRdUBzr-k8OAy7RRJszHX7LYLU0
