# 数据库配置
spring:
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 724721900@qq.com
    #QQ邮箱的授权码
    password: nfwapzuvndtvbcef
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #不加这句则默认为myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 100MB
      # 单个文件的最大值
      max-file-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 服务
server:
  port: 80
# 文件上传路径配置
file:
  # 静态资源对外暴露的访问路径
  staticAccessPath: /static/files/**
  #文件上传目录
  uploadFolder: E:/javaAndMore/projectspace/jbhim/public/files/
  staticAccessUrl: http://localhost/static/files/


#设置一个邮件发送人
jbhim:
  mail:
    sender: 724721900@qq.com
